[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_transfer = "5a4U1aJy23hnXWG4adUJK4Y6t7tvp3XiCTDg7Eoj6ijS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/topcoder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
